name: farm_buddy
description: A simple farm management app for small-scale farmers.

publish_to: 'none' # This prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Local storage
  shared_preferences: ^2.0.15

  # Additional dependencies (optional, remove if not needed)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Include linting rules for analyzing the code
  lint: ^ 2.3.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
